blank_issues_enabled: false
contact_links:
  - name: Feedback, questions & ideas (Discussions)
    url: https://github.com/Dan-Berg-Projects/pure-data-playing-cards-selfhost/discussions
    about: Share feedback, ask a question, or suggest and upvote ideas here.
